// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "c35ea420-b73c-450e-ab48-8abbfdb9af19");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575380974);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575381094);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575293670);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575380734);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575380614);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575380854);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575381334);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575381214);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 808960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575313077);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fcdfd48d-8163-4056-8a0c-9b05410a789b}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575360000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575380593892");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575382422892");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575380589477");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575384189477");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001400");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575380586");
user_pref("browser.slowStartup.averageTime", 4780);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575313082491");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "5843d8c8be3a4bf4adf737bfe1cbf2d7");
user_pref("extensions.blocklist.lastModified", "Tue, 03 Dec 2019 12:46:24 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575380977);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001400");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"054c54de-fc3b-46ad-a2b0-7d61d48f1158\",\"screenshots@mozilla.org\":\"f68ec669-64fa-4e53-b216-ed30a678c627\",\"webcompat-reporter@mozilla.org\":\"308bc839-4f81-4074-9b59-b712c185b4c0\",\"webcompat@mozilla.org\":\"668a9d5b-4bfe-4927-b916-bf5feacd0dad\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575313116);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "5f63f6ee-abe8-4b80-b83b-8769fd6d5800");
user_pref("security.sandbox.plugin.tempDirSuffix", "5c239d49-8de6-47db-a9be-b129e257bdcd");
user_pref("services.blocklist.addons.checked", 1575380897);
user_pref("services.blocklist.gfx.checked", 1575380897);
user_pref("services.blocklist.onecrl.checked", 1575380897);
user_pref("services.blocklist.pinning.checked", 1575380897);
user_pref("services.blocklist.plugins.checked", 1575380897);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1575377184560\"");
user_pref("services.settings.last_update_seconds", 1575380897);
user_pref("services.settings.main.language-dictionaries.last_check", 1575380897);
user_pref("services.settings.main.sites-classification.last_check", 1575380897);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575380583);
user_pref("toolkit.telemetry.cachedClientID", "7fe82866-50f2-4621-9f97-3ba8576b9cd4");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
